DemoProject/Areas/Custom/Controllers/UserDataController.cs
using DAL;
using DAL.Service;
using DemoProject.Areas.Custom.Models;
using DemoProject.Core.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoProject.Areas.Custom.Controllers
{
    public class UserDataController : BaseController
    {
        IUserDataRepository _IUserData = BFactory.CreateUserData(string.Empty);
        // GET: Custom/UserData
        public ActionResult Index() {
            UserDataModel model = new UserDataModel();
                var user = _IUserData.UserData(this.LoginInfo.UserPK);
                model.PK = user.PK;
                model.Name = user.Name;
                model.H_TEL = user.H_TEL;
                model.M_TEL = user.M_TEL;
                model.EMAIL = user.EMAIL;
                model.ADDR = user.ADDR;
            return PartialView("_UserDataManage", model);
        }

        public ActionResult UpdateUserData(FormCollection collection) {
            UserDataModel model = new UserDataModel();
            var bResult = false;
            try {
                if (TryUpdateModel(model) && ModelState.IsValid) {
                    UserData user = new UserData {
                        PK = model.PK,
                        Name = model.Name,
                        H_TEL = model.H_TEL,
                        M_TEL = model.M_TEL,
                        ADDR = model.ADDR,
                        EMAIL = model.EMAIL
                    };
                    bResult = _IUserData.UpdateUserData(user);
                }
            }
            catch {
                bResult = false;
            }
            ViewBag.Success = bResult;
            return PartialView("_UserDataManage", model);
        }
    }
}

DemoProject/Areas/Custom/Views/UserData/_UserDataManage.cshtml
@model DemoProject.Areas.Custom.Models.UserDataModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>個人基本資料管理</title>
    <script type="text/javascript">
        $(document).ready(function () {
            $("form[id='UserDataForm']").submit(function () {
                $.post($(this).attr("action"), $(this).serialize(), function (response) {
                    $("#Content").html(response);
                });
                return false;
            });
        });
    </script>
</head>
<body>
    <div id="DivUserData">
        @using (Html.BeginForm("UpdateUserData", "UserData", FormMethod.Post, new { id = "UserDataForm" })) { 
            <table border="1">
                <tr>
                    <th>@Html.LabelFor(m => m.Name)</th>
                    <td>@Html.EditorFor(m=>m.Name) @Html.HiddenFor(m=>m.PK)</td>
                </tr>
                <tr>
                    <th>@Html.LabelFor(m=>m.H_TEL)</th>
                    <td>@Html.EditorFor(m=>m.H_TEL)</td>
                </tr>
                <tr>
                    <th>@Html.LabelFor(m=>m.M_TEL)</th>
                    <td>@Html.EditorFor(m=>m.M_TEL)</td>
                </tr>
                <tr>
                    <th>@Html.LabelFor(m => m.ADDR)</th>
                    <td>@Html.EditorFor(m => m.ADDR)</td>
                </tr>
                <tr>
                    <th>@Html.LabelFor(m => m.EMAIL)</th>
                    <td>@Html.EditorFor(m => m.EMAIL)</td>
                </tr>
                <tr>
                    <td colspan="2">
                        <input type="submit" value="儲存" />
                    </td>
                </tr>
            </table>
        }
    </div>
</body>
</html>
@if (ViewBag.Success != null) {
    var bresult = (bool)ViewBag.Success;
    if (bresult) {
        <script type="text/javascript">
            alert('儲存成功!');
        </script>
    }
    else {
        var message = "儲存失敗!\\n\\r";
        var modelStateErrors = ViewData.ModelState.Keys.SelectMany(key => ViewData.ModelState[key].Errors);
        foreach (var item in modelStateErrors) {
            message += item.ErrorMessage + "\\n\\r";
        }
        <script type="text/javascript">
            alert('@message');
        </script>
    }
}